-- AUTO-GENERATED LAUNCHER FOR LOCAL DEVELOPMENT.
--
-- This file is automatically generated by `npm run setup-resolve` from the
-- template in src-tauri/resources/AutoSubs (Dev).lua. It points Resolve at your
-- local AutoSubs source tree and starts the core server in development mode.
-- (`npm run setup-resolve` also generates `AutoSubs (Dev).scriptlib` in the
-- Scripts root, which auto-starts this dev bridge when Resolve launches.)
--
-- NO EDITING NEEDED: just run `npm run setup-resolve` from AutoSubs-App/.
-- The copy of this file that lives in your DaVinci Resolve scripts folder is
-- generated from the template in the repo (src-tauri/resources/AutoSubs (Dev).lua)
-- by running, from the AutoSubs-App directory:
--
--     npm run setup-resolve
--
-- That command bakes the absolute path to your local checkout into the line
-- below, so this launcher is fully self-contained: it points Resolve directly
-- at the AutoSubs source tree and starts the core server in development mode.
-- It does NOT require AutoSubs to be installed normally first, and it never
-- loads AutoSubs.lua. Edits to the Lua modules are picked up the next time you
-- run this script from Resolve (no rebuild needed).

-- `npm run setup-resolve` replaces the placeholder below with the absolute path
-- to the repo's `src-tauri/resources` folder.
local resources_folder = [[__AUTOSUBS_RESOURCES_FOLDER__]]

if resources_folder == "__AUTOSUBS_RESOURCES_FOLDER__" then
    error(
        "'AutoSubs (Dev).lua' has not been generated yet. Run `npm run setup-resolve` " ..
        "from the AutoSubs-App directory to create a configured copy in your " ..
        "DaVinci Resolve scripts folder."
    )
end

-- Load the bootstrap via loadfile (the sandboxed scripting state has no
-- require/package); it sets up module loading and starts the core server.
-- mode = "manual": running this script restarts the bridge against your repo
-- checkout (it stops any resident bridge first, including the startup one).
local bootstrap_path = resources_folder .. "/modules/bootstrap.lua"
local boot = assert(loadfile(bootstrap_path))()

-- No executable path is needed in dev mode: the core server never launches the
-- desktop app while dev mode is enabled.
return boot(resources_folder, "", true, { mode = "manual" })

