import { Model } from "@/types/interfaces";

/**
 * Centralized model definitions for AutoSubs
 * These model definitions are used throughout the application
 * to ensure consistency in model information display
 */
export const models: Model[] = [
  {
    value: "tiny",
    label: "models.tiny.label",
    description: "models.tiny.description",
    size: "80MB",
    ram: "1GB",
    image: "/hummingbird.png",
    details: "models.tiny.details",
    languageSupport: { kind: "multilingual" },
    isDownloaded: false,
  },
  {
    value: "tiny.en",
    label: "models.tiny_en.label",
    description: "models.tiny_en.description",
    size: "80MB",
    ram: "1GB",
    image: "/hummingbird.png",
    details: "models.tiny_en.details",
    languageSupport: { kind: "single_language", language: "en" },
    isDownloaded: false,
  },
  {
    value: "base",
    label: "models.base.label",
    description: "models.base.description",
    size: "150MB",
    ram: "1GB",
    image: "/otter.png",
    details: "models.base.details",
    languageSupport: { kind: "multilingual" },
    isDownloaded: false,
  },
  {
    value: "base.en",
    label: "models.base_en.label",
    description: "models.base_en.description",
    size: "150MB",
    ram: "1GB",
    image: "/otter.png",
    details: "models.base_en.details",
    languageSupport: { kind: "single_language", language: "en" },
    isDownloaded: false,
  },
  {
    value: "small",
    label: "models.small.label",
    description: "models.small.description",
    size: "480MB",
    ram: "2GB",
    image: "/fox.png",
    details: "models.small.details",
    languageSupport: { kind: "multilingual" },
    isDownloaded: false,
  },
  {
    value: "small.en",
    label: "models.small_en.label",
    description: "models.small_en.description",
    size: "480MB",
    ram: "2GB",
    image: "/fox.png",
    details: "models.small_en.details",
    languageSupport: { kind: "single_language", language: "en" },
    isDownloaded: false,
  },
  {
    value: "medium",
    label: "models.medium.label",
    description: "models.medium.description",
    size: "1.5GB",
    ram: "5GB",
    image: "/owl.png",
    details: "models.medium.details",
    languageSupport: { kind: "multilingual" },
    isDownloaded: false,
  },
  {
    value: "medium.en",
    label: "models.medium_en.label",
    description: "models.medium_en.description",
    size: "1.5GB",
    ram: "5GB",
    image: "/owl.png",
    details: "models.medium_en.details",
    languageSupport: { kind: "single_language", language: "en" },
    isDownloaded: false,
  },
  {
    value: "large-v3-turbo",
    label: "models.large_v3_turbo.label",
    description: "models.large_v3_turbo.description",
    size: "1.6GB",
    ram: "6GB",
    image: "/phoenix.png",
    details: "models.large_v3_turbo.details",
    languageSupport: { kind: "multilingual" },
    isDownloaded: false,
  },
  {
    value: "large-v3",
    label: "models.large_v3.label",
    description: "models.large_v3.description",
    size: "3.1GB",
    ram: "10GB",
    image: "/elephant.png",
    details: "models.large_v3.details",
    languageSupport: { kind: "multilingual" },
    isDownloaded: false,
  },
];
