-- AUTO-GENERATED by Resolve-Integration/scripts/build-macro.mjs
-- Source of truth: Resolve-Integration/macro-src/. DO NOT EDIT BY HAND.
return {
	version = 1,
	blocks = {
		ApplyAnimationLevel = [[
return function(comp, tool)
	-- Get current spline settings to be modified
	local spline = comp:FindTool(tool:GetData("DelaySpline"))
	local settings = spline:SaveSettings()

	if tool:GetInput("AnimationLevel") == 1 then
		-- Restore word timing keyframes
		local wordTiming = tool:GetData("WordTiming")
		local keyframes = loadstring(tool:GetData("ConvertToDelayKeyframes"))()(wordTiming)

		settings.Tools[spline.Name].KeyFrames = keyframes
		spline:LoadSettings(settings)
	else
		-- Remove word timing keyframes
		-- TODO: Investigate if easier to set Order type to Automatic
		local text = tool:GetInput("Text")
		if text and #text > 0 then
			settings.Tools[spline.Name].KeyFrames = {
				[#text] = { 0, Flags = { StepIn = true } },
			}
			spline:LoadSettings(settings)
		end
	end

	-- Scale type must be changed to line or word (if being utilised)
	if tool:GetInput("PopInEnabled") == 1 then
		loadstring(tool:GetData("SetAnimations"))()(comp, tool)
	end
end
]],
		ApplyHighlight = [[
					return function(comp, tool)
						local STYLES = {"Fill", "Outline", "Shadow", "Bubble"}
						local STYLE_INDEX = {
							Fill = 1,
							Outline = 2, 
							Shadow = 3,
							Bubble = 4
						}
						local CHANNELS = { "Red", "Green", "Blue" } -- exclude opacity for now as it interferes with other effects
						local INTERNAL_CODES = { Red = 2401, Green = 2402, Blue = 2403, Enabled = 2000 } -- Note: Opacity = 2600

						loadstring(tool:GetData("UpdateAllStyleColors"))()(comp, tool)

						-- Function to retrieve the base style for non-highlighted words
						-- @param template: The template tool
						-- @param styleKey: The style key (e.g. "Fill", "Outline", etc.)
						-- @return: A table containing the base style values
						local function get_current_style(styleKey)
							local base = {}
							
							-- Get color values for all channels (Red, Green, Blue)
							for _, channel in ipairs(CHANNELS) do
								base[channel] = tool:GetInput(styleKey .. "Color" .. channel)
							end

							-- Handle enabled state differently for Bubble vs other styles
							local template = comp:FindTool("Template")
							local isBubbleStyle = styleKey == "Bubble"

							-- Bubble must be enabled at the template level or will not work with character-level styling
							template:SetInput("Enabled4", isBubbleStyle and 1 or 0)

							if isBubbleStyle then
								base["Enabled"] = 0 -- only highlighted words should have bubble enabled (disabled for base style)
							else
								base["Enabled"] = tool:GetInput(styleKey .. "Enabled")
							end

							return base
						end

						-- Build a StyledText Array where word at `activeIndex` uses `highlight` colors and the rest use `base`
						local function build_style_array(wordTiming, activeIndex, highlight, base, styleId)
							local array = {}
							for j, word in ipairs(wordTiming) do
								local style = j == activeIndex and highlight or base
								for key, internalCode in pairs(INTERNAL_CODES) do
									table.insert(array, {
										internalCode,
										word.startIndex,
										word.endIndex,
										Value = style[key],
										__flags = 256,
										Index = styleId
									})
								end
							end
							return array
						end

						-- Create a single StyledText keyframe value
						local function make_keyframe(index, styleArray)
							return {
								index,
								Value = {
									__ctor = "StyledText", -- internal id to designate this as a StyledText object
									Array = styleArray,
									Flags = { StepIn = true, LockedY = true, __flags = 256 }
								},
							}
						end

						local function round(x)
							return math.floor(x + 0.5)
						end

						local follower = comp:FindTool("Follower1")
						local characterLevelStyling = follower.Text:GetConnectedOutput():GetTool()
						local spline = characterLevelStyling.CharacterLevelStyling:GetConnectedOutput():GetTool()

						local wordTiming = tool:GetData("WordTiming")

						local highlight = {
    						Red = tool:GetInput("HighlightColorRed"),
    						Green = tool:GetInput("HighlightColorGreen"),
    						Blue = tool:GetInput("HighlightColorBlue"),
							Enabled = 1
						}

						-- (0=Fill, 1=Outline, 2=Shadow, 3=Bubble)
						local styleId = tool:GetInput("HighlightStyle")

						-- TextPlus input suffixes are 1-based (e.g. Red1, Red2).
						-- CharacterLevelStyling style indices appear to be 0-based.

						-- local animationLength = comp:FindTool("Template"):GetInput("AnimationLength")
						-- local fps = tonumber(comp:GetPrefs("Comp.FrameFormat.Rate")) or 30
						-- local transitionFrames = round(animationLength * fps)
						local transitionFrames = 0

						-- +1 required: styleId is 0-based but Lua arrays are 1-based
						local styleKey = STYLES[styleId + 1]
						local base = get_current_style(styleKey)
						local keyframes = {}
						local keyframeIndex = 0
						for i, word in ipairs(wordTiming) do
							local startFrame = word.startFrame + (i > 1 and transitionFrames or 0)
							local styleArray = build_style_array(wordTiming, i, highlight, base, styleId)

							keyframes[startFrame] = make_keyframe(keyframeIndex, styleArray)
							keyframeIndex = keyframeIndex + 1

							if i < #wordTiming then
								-- Holds the style constant until just before the next word starts, so the
								-- transition only occurs near the word boundary rather than fading from
								-- the beginning of the current word all the way to the next
								keyframes[word.endFrame - 1] = make_keyframe(keyframeIndex, styleArray)
								keyframeIndex = keyframeIndex + 1
							end
						end

						spline:SetKeyFrames(keyframes, true)
					end
]],
		ApplyWordMarkers = [[
return function(comp, tool)
	-- Get timeline item that contains this composition
	local getTimelineItem = loadstring(tool:GetData("GetTimelineItem"))()
	local item = getTimelineItem(comp)
	if not item then return end

	-- Get follower delay spline
	local spline = comp:FindTool(tool:GetData("DelaySpline"))

	-- Get comp offset
	local offset = comp:GetAttrs("COMPN_RenderStart")

	-- Collect marker positions from timeline
	local markers = item:GetMarkers()
	local markerFrames = {}
	for frame, markerInfo in pairs(markers) do
		if markerInfo["customData"] == "AutoSubs" then
			table.insert(markerFrames, frame - offset)
		end
	end

	-- Sort markers by frame number
	table.sort(markerFrames)

	-- Split text into words
	local text = tool:GetInput("Text")
	local words = {}
	for word in text:gmatch("%S+") do
		table.insert(words, word)
	end
	
	-- UTF-8 aware character count
	local function utf8len(s)
		local _, count = s:gsub("[^\128-\191]", "")
		return count
	end

	-- Build intermediate word timing format
	local wordTiming = {}
	local count = math.min(#markerFrames, #words)
	local charIndex = 0
	
	for i = 1, count do
		local wordText = words[i]
		if i > 1 then
			wordText = " " .. wordText
		end

		local length = utf8len(wordText)
		local startFrame = markerFrames[i]
		local endFrame
	
		if i < count then
			endFrame = markerFrames[i + 1]
		else
			endFrame = startFrame
		end
	
		table.insert(wordTiming, {
			["startIndex"] = charIndex,
			["endIndex"] = charIndex + length - 1,
			["startFrame"] = startFrame,
			["endFrame"] = endFrame,
		})

		charIndex = charIndex + length
	end
	
	-- Apply word timing (update spline, store data, refresh highlight)
	loadstring(tool:GetData("ApplyWordTiming"))()(comp, tool, wordTiming)

	-- Clean up markers
	while item:DeleteMarkerByCustomData("AutoSubs") do end
end
]],
		ApplyWordTiming = [[
return function(comp, tool, wordTiming)
	local spline = comp:FindTool(tool:GetData("DelaySpline"))

	local settings = spline:SaveSettings()
	if tool:GetInput("AnimationLevel") == 1 then
		local keyframes = loadstring(tool:GetData("ConvertToDelayKeyframes"))()(wordTiming)
		settings.Tools[spline.Name].KeyFrames = keyframes
	else
		local text = tool:GetInput("Text")
		settings.Tools[spline.Name].KeyFrames = {
			[#text] = { 0, Flags = { StepIn = true } },
		}
	end
	spline:LoadSettings(settings)

	tool:SetData("WordTiming", wordTiming)
	loadstring(tool:GetData("UpdateHighlight"))()(comp, tool)
end
]],
		ConvertToDelayKeyframes = [[
return function(wordTiming)
	local keyframes = {}
	for _, word in ipairs(wordTiming) do
		keyframes[word.startIndex] = { word.startFrame, Flags = { StepIn = true } }
	end
	return keyframes
end
]],
		GetInputValues = [[
return function(tool)
	local keys = tool:GetData("InputKeys")
	local settings = {}
	for _, key in ipairs(keys) do
		settings[key] = tool:GetInput(key)
	end
	return settings
end
]],
		GetTimelineItem = [[
return function(comp)
	-- Final attempt at getting Resolve object for Free version users
	local resolve = _G.resolve 
		or (fusion and fusion.GetResolve and fusion:GetResolve()) 
		or (app and app.GetResolve and app:GetResolve()) 
		or (bmd and bmd.scriptapp and bmd.scriptapp("Resolve"))
		or (comp:GetApp() and comp:GetApp():GetResolve())

	-- Strict check: must be a valid object (userdata or table)
	if type(resolve) ~= "userdata" and type(resolve) ~= "table" then
		print("[CHECK-123] This feature (Markers) requires DaVinci Resolve Studio or enabled Scripting API.")
		return nil
	end

	local projectManager = resolve:GetProjectManager()
	local currentProject = projectManager:GetCurrentProject()
	local timeline = currentProject:GetCurrentTimeline()

	local function itemContainsComp(timelineItem, targetComp)
		if timelineItem:GetFusionCompCount() == 0 then
			return false
		end

		return timelineItem:GetFusionCompByIndex(1) == targetComp
	end
	
	-- Search from top track down (subtitles usually on top track - faster)
	local videoTrackCount = timeline:GetTrackCount("video")
	for trackIndex = videoTrackCount, 1, -1 do
		local itemsOnTrack = timeline:GetItemListInTrack("video", trackIndex)
		
		for _, timelineItem in ipairs(itemsOnTrack or {}) do
			if itemContainsComp(timelineItem, comp) then
				return timelineItem
			end
		end
	end
	
	return nil
end
]],
		RemoveHighlight = [[
return function(comp, tool)
	local follower = comp:FindTool("Follower1")
	local characterLevelStyling = follower.Text:GetConnectedOutput():GetTool()
	local spline = characterLevelStyling.CharacterLevelStyling:GetConnectedOutput():GetTool()
	loadstring(tool:GetData("UpdateAllStyleColors"))()(comp, tool)

	local keyframes = {
		[0] = {
	        0,                         -- index of keyframe in the array (0-based) - kinda random - why?
	        Value = {
	            __ctor = "StyledText", -- internal id to designate this as a StyledText object
	            Array = {}, -- empty array uses default styling
	            Flags = { StepIn = true, LockedY = true, __flags = 256 }
	        },
	    },
	}

	spline:SetKeyFrames(keyframes, true)

	-- Disable Bubble (enabled specifically for highlight)
	local template = comp:FindTool("Template")
	template:SetInput("Enabled4", 0)
end
]],
		SetAnimations = [[
-- Registry-driven animation orchestrator.
--
-- Replaces the old hard-coded fade coupling. Fade is now applied exactly once,
-- when FadeEnabled is on OR any enabled animation declares `usesFade = true`
-- (see macro-src/animations/*.lua). Adding an animation no longer requires
-- editing this file — just drop a descriptor in animations/ and list it in
-- animations/_registry.lua.
return function(comp, tool)
	-- Ordered list of animation descriptors ({ id, label, controlKey, usesFade,
	-- apply, reset, [flat] }). Assembled by build-macro.mjs.
	local registry = loadstring(tool:GetData("AnimationRegistry"))()

	local animationLength = tool:GetInput("AnimationLength")
	local animationLevel = tool:GetInput("AnimationLevel")
	local animationMode = tool:GetInput("AnimationMode") or 2

	local follower = comp:FindTool("Follower1")
	local animStretcher = comp:FindTool("AnimationKeyframeStretcher")
	local orderStretcher = comp:FindTool("OrderKeyframeStretcher")
	local animSpline = animStretcher.Keyframes:GetConnectedOutput():GetTool()
	local orderSpline = orderStretcher.Keyframes:GetConnectedOutput():GetTool()

	-- Calculate animation frames
	local fps = tonumber(comp:GetPrefs("Comp.FrameFormat.Rate")) or 30
	local function round(x) return math.floor(x + 0.5) end
	local frames = round(animationLength * fps)
	local animInEnd = frames
	local animOutStart = 100 - frames

	-- Shared context handed to every animation's apply()/flat() so new animations
	-- never need new positional arguments.
	local ctx = {
		comp = comp,
		tool = tool,
		follower = follower,
		animStretcher = animStretcher,
		animSpline = animSpline,
		animInEnd = animInEnd,
		animOutStart = animOutStart,
		animationLevel = animationLevel,
		mode = animationMode,
		fps = fps,
	}

	-- 1. Reset every animation to a clean slate (idempotent).
	for _, anim in ipairs(registry) do
		if anim.reset then anim.reset(follower) end
	end

	-- 2. Determine enabled animations and whether a fade is needed.
	local enabled = {}
	local needsFade = tool:GetInput("FadeEnabled") == 1
	local fadeAnim = nil
	for _, anim in ipairs(registry) do
		if anim.id == "fade" then fadeAnim = anim end
		if anim.controlKey and tool:GetInput(anim.controlKey) == 1 then
			table.insert(enabled, anim)
			if anim.usesFade then needsFade = true end
		end
	end

	-- 3. Apply the single shared fade (or flat opacity) exactly once.
	if fadeAnim then
		if needsFade then
			fadeAnim.apply(ctx)
		else
			fadeAnim.flat(ctx)
		end
	end

	-- 4. Apply each enabled animation's own effect (the fade module is a no-op here).
	for _, anim in ipairs(enabled) do
		if anim.id ~= "fade" then
			anim.apply(ctx)
		end
	end

	-- 5. Set stretcher time ranges
	animStretcher:SetInput("StretchStart", animInEnd)
	animStretcher:SetInput("StretchEnd", animOutStart)

	-- Configure order spline for out animation (animate entire line out, not word by word)
	orderSpline:SetKeyFrames({
		[animOutStart-1] = { 6, Flags = { StepIn = true } }, -- "Manual Curve"
		[animOutStart] = { 0, Flags = { StepIn = true } },   -- "Automatic" (everything animates together)
	}, true)
	orderSpline:SetInput("StretchEnd", animOutStart)
end
]],
		SetInputValues = [[
return function(comp, tool, settings)
	for key, value in pairs(settings) do
		tool:SetInput(key, value)
	end

	-- Update animation and highlight
	loadstring(tool:GetData("SetAnimations"))()(comp, tool)
	loadstring(tool:GetData("UpdateHighlight"))()(comp, tool)
end
]],
		ShowWordMarkers = [[
return function(comp, tool)
	local getTimelineItem = loadstring(tool:GetData("GetTimelineItem"))()
	local item = getTimelineItem(comp)
	if not item then return end

	local wordTiming = tool:GetData("WordTiming")
	if not wordTiming or #wordTiming == 0 then
		print("[AutoSubs] No word timing data found. Please transcribe or add text first.")
		return
	end

	-- Clear existing markers
	while item:DeleteMarkerByCustomData("AutoSubs") do end

	print("[AutoSubs] Generating markers for " .. #wordTiming .. " words.")

	local offset = comp:GetAttrs("COMPN_RenderStart")
	for i, word in ipairs(wordTiming) do
		if word.startFrame then
			item:AddMarker(word.startFrame + offset, "Blue", "Word " .. i, "", 1, "AutoSubs")
		end
	end
end
]],
		ToggleHighlight = [[
					return function(comp, tool)
						local isEnabled = tool:GetInput("HighlightEnabled") == 1
						local func = isEnabled
        					and tool:GetData("ApplyHighlight") 
        					or tool:GetData("RemoveHighlight")
    					loadstring(func)()(comp, tool)
					end
]],
		UpdateAllStyleColors = [[
return function(comp, tool)
	local template, follower = comp:FindTool("Template"), comp:FindTool("Follower1")
	local types = {"Fill", "Outline", "Shadow", "Bubble"}
	
	for _, type in ipairs(types) do
		local id = ({Fill="1", Outline="2", Shadow="3", Bubble="4"})[type]
		
		local value = tool:GetInput(type .. "Enabled")
		template:SetInput("Enabled" .. id, value)
		follower:SetInput("Enabled" .. id, value)
		
		for _, key in ipairs({"Red", "Green", "Blue", "Thickness"}) do
			if type == "Outline" and key == "Thickness" then
				local value = tool:GetInput(type .. "Thickness")
				template:SetInput(key .. id, value)
				follower:SetInput(key .. id, value)
			else
				local value = tool:GetInput(type .. "Color" .. key)
				template:SetInput(key .. id, value)
				follower:SetInput(key .. id, value)
			end
		end
	end
end
]],
		UpdateHighlight = [[
					return function(comp, tool)
						-- Must update Highlight keyframes (if enabled)
						local isEnabled = tool:GetInput("HighlightEnabled") == 1
						if isEnabled then
    					    loadstring(tool:GetData("ApplyHighlight"))()(comp, tool)
						end
					end
]],
		UpdateStyleColor = [[
return function(comp, tool, type)
	local id = ({Fill="1", Outline="2", Shadow="3", Bubble="4"})[type]
	local template, follower = comp:FindTool("Template"), comp:FindTool("Follower1")

	local value = tool:GetInput(type .. "Enabled")
	template:SetInput("Enabled" .. id, value)
	follower:SetInput("Enabled" .. id, value)
	
	for _, key in ipairs({"Red", "Green", "Blue", "Thickness"}) do
		if type == "Outline" and key == "Thickness" then
			local value = tool:GetInput(type .. "Thickness")
			template:SetInput(key .. id, value)
			follower:SetInput(key .. id, value)
		else
			local value = tool:GetInput(type .. "Color" .. key)
			template:SetInput(key .. id, value)
			follower:SetInput(key .. id, value)
		end
	end

	loadstring(tool:GetData("UpdateHighlight"))()(comp, tool)
end
]],
		UpdateTextContent = [[
return function(comp, tool, text)
	local function utf8len(s)
		local _, count = s:gsub("[^\128-\191]", "")
		return count
	end

	-- Split text into words
	local words = {}
	for word in text:gmatch("%S+") do
		table.insert(words, word)
	end

	local wordTiming = tool:GetData("WordTiming")
	if not wordTiming then return end

	local oldWordCount = #wordTiming
	local newWordCount = #words
	local hasExistingWords = oldWordCount > 0

	-- Determine a frames-per-character rate to dynamically estimate new word durations.
	local defaultFrameRate = tonumber(comp:GetPrefs("Comp.FrameFormat.Rate")) or 30
	-- Default speaking speed: ~15 characters per second
	local defaultFramesPerChar = defaultFrameRate / 15
	local framesPerChar = defaultFramesPerChar

	-- Calculate pacing from existing words if available
	if hasExistingWords then
		local totalFrames = 0
		local totalChars = 0
		-- Sum up the durations and lengths of existing words to analyze the speaker's true pacing.
		for j = 1, oldWordCount do
			local duration = wordTiming[j].endFrame - wordTiming[j].startFrame
			local length = wordTiming[j].endIndex - wordTiming[j].startIndex + 1
			-- Only average words with valid timings and non-zero character counts.
			if duration > 0 and length > 0 then
				totalFrames = totalFrames + duration
				totalChars = totalChars + length
			end
		end
		
		-- If we have valid historical pacing data, use it.
		if totalChars > 0 then
			framesPerChar = totalFrames / totalChars
		end
	end

	-- If words were removed, delete their corresponding timing data from the end of the list first.
	if newWordCount < oldWordCount then
		for i = oldWordCount, newWordCount + 1, -1 do
			table.remove(wordTiming, i)
		end
	end

	-- Traverse all words to add new timings and recompute absolute character indices.
	local currentFrame = hasExistingWords and wordTiming[oldWordCount].endFrame or 0
	local charIndex = 0

	-- Used for clamping words to be within clip range
	local compositionEndFrame = comp:GetAttrs("COMPN_RenderEnd") or 1000

	for i = 1, newWordCount do
		local wordText = words[i]
		-- Reconstruct spaces between words to match the combined subtitle text structure.
		if i > 1 then
			wordText = " " .. wordText
		end

		-- Use UTF-8 safe length to accurately handle multi-byte characters and map index boundaries.
		local length = utf8len(wordText)

		if i > oldWordCount then
			-- Estimate timing for newly added words scaled by their character length.
			local startFrame = currentFrame
			local wordLength = utf8len(words[i])
			local duration = math.max(1, math.floor(wordLength * framesPerChar))
			local endFrame = startFrame + duration

			table.insert(wordTiming, {
				["startIndex"] = charIndex,
				["endIndex"] = charIndex + length - 1,
				["startFrame"] = math.min(startFrame, compositionEndFrame - 1),
				["endFrame"] = math.min(endFrame, compositionEndFrame - 1),
			})
			
			currentFrame = endFrame
		else
			-- Update character boundaries for existing words.
			wordTiming[i].startIndex = charIndex
			wordTiming[i].endIndex = charIndex + length - 1
		end

		-- Advance the character playhead for the next word.
		charIndex = charIndex + length
	end

	loadstring(tool:GetData("ApplyWordTiming"))()(comp, tool, wordTiming)
end
]],
		AnimationRegistry = [[
	local helpers = (function()
	-- Shared animation helpers. Available to animation descriptors as the upvalue
	-- `helpers` (wired in by build-macro.mjs when it assembles the AnimationRegistry
	-- chunk). Files prefixed with `_` are NOT animation descriptors and are skipped
	-- by the registry.
	return {
		-- Remove the XYPath modifiers from the follower Offset inputs (slide-up uses
		-- these to animate vertical position).
		RemoveOffsetModifiers = function(follower)
			for i = 1, 3 do
				local offsetProp = "Offset" .. i
				local offsetInput = follower[offsetProp]
				if offsetInput then
					local output = offsetInput:GetConnectedOutput()
					if output then
						local xyPath = output:GetTool()
						-- Fusion exposes no tool-type query here, so we fall back to
						-- matching the tool name. slide_up.lua adds these via
						-- AddModifier(offsetProp, "XYPath"), whose default name contains
						-- "XYPath"; this guards against detaching an unrelated modifier.
						if xyPath and xyPath.Name:match("XYPath") then
							follower[offsetProp] = nil
						end
					end
				end
			end
		end,
	}
	end)()

	local fade_helper = (function()
	-- Shared fade implementation: the single source of truth for the caption
	-- fade-in / fade-out opacity curve.
	--
	-- set_animations applies this exactly once per update, either because the user
	-- enabled FadeEnabled directly, or because an enabled animation declares
	-- `usesFade = true` (pop-in / slide-up look nicer over a fade). Do NOT duplicate
	-- this curve into other animations.
	--
	-- Available to animation descriptors as the upvalue `fade_helper` (wired in by
	-- build-macro.mjs when it assembles the AnimationRegistry chunk).
	return {
		-- Connect the follower Opacity to the animation stretcher and write the fade
		-- spline. `ctx` is the shared context built in set_animations.lua.
		apply = function(follower, ctx)
			local animStretcher = ctx.animStretcher
			local animSpline = ctx.animSpline
			local animInEnd = ctx.animInEnd
			local animOutStart = ctx.animOutStart
			local mode = ctx.mode

			follower.Opacity1 = animStretcher.Result
			follower.Opacity2 = animStretcher.Result
			follower.Opacity3 = animStretcher.Result
			follower.Opacity4 = animStretcher.Result

			local keyframes
			if mode == 0 then
				-- In only
				keyframes = {
					[0] = { 0 },
					[animInEnd] = { 1, LH = { -animInEnd, 0 } },
					[100] = { 1 },
				}
			elseif mode == 1 then
				-- Out only
				keyframes = {
					[0] = { 1 },
					[animOutStart] = { 1 },
					[100] = { 0 },
				}
			else
				-- Both (default)
				keyframes = {
					[0] = { 0 },
					[animInEnd] = { 1, LH = { -animInEnd, 0 } },
					[animOutStart] = { 1 },
					[100] = { 0 },
				}
			end

			animSpline:SetKeyFrames(keyframes, true)
			print("Applied Fade animation (mode: " .. mode .. ")")
		end,
		-- Flat opacity = 1 across the whole clip (used when nothing needs a fade).
		flat = function(follower, ctx)
			local animStretcher = ctx.animStretcher
			local animSpline = ctx.animSpline

			follower.Opacity1 = animStretcher.Result
			follower.Opacity2 = animStretcher.Result
			follower.Opacity3 = animStretcher.Result
			follower.Opacity4 = animStretcher.Result
			animSpline:SetKeyFrames({
				[0] = { 1, Flags = { StepIn = true } },
				[100] = { 1, Flags = { StepIn = true } },
			}, true)
		end,
	}
	end)()

	local fade = (function()
	-- Fade animation descriptor.
	--
	-- Fade *is* the fade, so usesFade = false. The actual opacity curve lives in
	-- the shared `fade_helper` (single source of truth); set_animations decides
	-- when to call apply() vs flat().
	return {
		id = "fade",
		label = "Fade",
		controlKey = "FadeEnabled",
		usesFade = false,
		-- Real fade-in/out.
		apply = function(ctx)
			fade_helper.apply(ctx.follower, ctx)
		end,
		-- Flat opacity = 1 (no fade). Called by set_animations when nothing needs a fade.
		flat = function(ctx)
			fade_helper.flat(ctx.follower, ctx)
		end,
		reset = function(follower)
			follower.Opacity1 = nil
			follower.Opacity2 = nil
			follower.Opacity3 = nil
			follower.Opacity4 = nil
			follower:SetInput("Opacity1", 1)
			follower:SetInput("Opacity2", 1)
			follower:SetInput("Opacity3", 1)
			follower:SetInput("Opacity4", 1)
		end,
	}
	end)()

	local pop_in = (function()
	-- Pop-in animation descriptor: KeyStretcher modifiers on the follower
	-- Word/Line size inputs scale the text up with a smooth ease-in.
	return {
		id = "popIn",
		label = "Pop In",
		controlKey = "PopInEnabled",
		usesFade = true, -- looks nicer over a fade; set_animations adds the fade once
		apply = function(ctx)
			local follower = ctx.follower
			local animInEnd = ctx.animInEnd
			local animOutStart = ctx.animOutStart
			local animationLevel = ctx.animationLevel
			local mode = ctx.mode

			local sizeKeyframes
			if mode == 0 then
				-- In only
				sizeKeyframes = {
					[0] = { 0.8 },
					[animInEnd] = { 1, LH = { -animInEnd, 0 } },
					[100] = { 1 },
				}
			elseif mode == 1 then
				-- Out only
				sizeKeyframes = {
					[0] = { 1 },
					[animOutStart] = { 1 },
					[100] = { 0.8 },
				}
			else
				-- Both (default)
				sizeKeyframes = {
					[0] = { 0.8 },
					[animInEnd] = { 1, LH = { -animInEnd, 0 } },
					[animOutStart] = { 1 },
					[100] = { 0 },
				}
			end
			local function applyStretchedKeyframes(propName)
				follower:AddModifier(propName, "KeyStretcherMod")
				local stretcher = follower[propName]:GetConnectedOutput():GetTool()
				if stretcher then
					stretcher:AddModifier("Keyframes", "BezierSpline")
					local spline = stretcher.Keyframes:GetConnectedOutput():GetTool()
					if spline then
						spline:SetKeyFrames(sizeKeyframes, true)
					end
					stretcher:SetInput("StretchStart", animInEnd)
					stretcher:SetInput("StretchEnd", animOutStart)
				end
			end
			local propX = animationLevel == 0 and "Line" or "Word"
			applyStretchedKeyframes(propX .. "SizeX")
			applyStretchedKeyframes(propX .. "SizeY")
			print("Applied PopIn animation (mode: " .. mode .. ")")
		end,
		reset = function(follower)
			follower.LineSizeX = nil
			follower.LineSizeY = nil
			follower.WordSizeX = nil
			follower.WordSizeY = nil
			follower:SetInput("LineSizeX", 1)
			follower:SetInput("LineSizeY", 1)
			follower:SetInput("WordSizeX", 1)
			follower:SetInput("WordSizeY", 1)
		end,
	}
	end)()

	local slide_up = (function()
	-- Slide-up animation descriptor: XYPath + KeyStretcher on the follower Offset
	-- inputs animate the text vertically with a smooth ease-in.
	return {
		id = "slideUp",
		label = "Slide Up",
		controlKey = "SlideUpEnabled",
		usesFade = true, -- looks nicer over a fade; set_animations adds the fade once
		apply = function(ctx)
			local follower = ctx.follower
			local animInEnd = ctx.animInEnd
			local animOutStart = ctx.animOutStart
			local mode = ctx.mode

			local yKeyframes
			if mode == 0 then
				-- In only
				yKeyframes = {
					[0] = { -0.1 },
					[animInEnd] = { 0, LH = { -animInEnd, 0 } },
					[100] = { 0 },
				}
			elseif mode == 1 then
				-- Out only
				yKeyframes = {
					[0] = { 0 },
					[animOutStart] = { 0 },
					[100] = { -0.1 },
				}
			else
				-- Both (default)
				yKeyframes = {
					[0] = { -0.1 },
					[animInEnd] = { 0, LH = { -animInEnd, 0 } },
					[animOutStart] = { 0 },
					[100] = { -0.1 },
				}
			end
			for i = 1, 3 do
				local offsetProp = "Offset" .. i
				follower:AddModifier(offsetProp, "XYPath")
				local xyPath = follower[offsetProp]:GetConnectedOutput():GetTool()
				if xyPath then
					xyPath:AddModifier("Y", "KeyStretcherMod")
					local yStretcher = xyPath.Y:GetConnectedOutput():GetTool()
					if yStretcher then
						yStretcher:AddModifier("Keyframes", "BezierSpline")
						local ySpline = yStretcher.Keyframes:GetConnectedOutput():GetTool()
						if ySpline then
							ySpline:SetKeyFrames(yKeyframes, true)
						end
						yStretcher:SetInput("StretchStart", animInEnd)
						yStretcher:SetInput("StretchEnd", animOutStart)
					end
				end
			end
			print("Applied SlideUp animation (mode: " .. mode .. ")")
		end,
		reset = function(follower)
			helpers.RemoveOffsetModifiers(follower)
		end,
	}
	end)()

	return { fade, pop_in, slide_up }
]],
	},
	data = {
		InputKeys = {
			"Font",
			"Style",
			"TextSize",
			"TextPosition",
			"FadeEnabled",
			"PopInEnabled",
			"SlideUpEnabled",
			"AnimationLength",
			"AnimationLevel",
			"AnimationMode",
			"HighlightExtendHorizontal",
			"HighlightExtendVertical",
			"HighlightRound",
			"HighlightColorRed",
			"HighlightColorGreen",
			"HighlightColorBlue",
			"FillEnabled",
			"FillColorRed",
			"FillColorGreen",
			"FillColorBlue",
			"OutlineEnabled",
			"OutlineThickness",
			"OutlineColorRed",
			"OutlineColorGreen",
			"OutlineColorBlue",
			"ShadowEnabled",
			"ShadowColorRed",
			"ShadowColorGreen",
			"ShadowColorBlue",
			"HighlightStyle",
			"HighlightEnabled",
		},
	},
}
