#!/bin/bash

# Paths to remove
echo "Uninstalling AutoSubs..."
files="${APPDATA}/Blackmagic Design/DaVinci Resolve/Support/Fusion/Scripts/Utility/"

# Loop through each file in the directory
for item in "${files}"*; do
    if [[ "$item" == *AutoSub* ]]; then
        rm -rf "$item"
        echo "Removed: $item"
    fi
done

echo "Uninstallation complete."
exit 0