import { CaptionPreset } from '@/types';

const EPOCH = '1970-01-01T00:00:00.000Z';

// Built-in presets ship empty `macroSettings` so the Fusion macro's own defaults
// are used. Users can create custom presets that capture inspector values via
// the `StartPresetEdit` / `CapturePresetSettings` Resolve endpoints.
export const BUILT_IN_PRESETS: CaptionPreset[] = [
    {
        id: 'builtin:default',
        name: 'AutoSubs Style',
        description: 'Each word pops in as it is spoken - blue outline - no highlight',
        builtIn: true,
        version: 1,
        createdAt: EPOCH,
        updatedAt: EPOCH,
        macroSettings: {
            Font: 'Arial Rounded MT Bold',
            Style: 'Regular',
            TextSize: 0.07,
            TextPosition: [0.5, 0.12, 0],
            FadeEnabled: 0,
            PopInEnabled: 1,
            SlideUpEnabled: 0,
            AnimationLength: 0.12,
            AnimationLevel: 1,
            AnimationMode: 0,
            HighlightExtendHorizontal: -0.03,
            HighlightExtendVertical: 0.06,
            HighlightRound: 0.2,
            HighlightColorRed: 0,
            HighlightColorGreen: 0.208,
            HighlightColorBlue: 1,
            FillEnabled: 1,
            FillColorRed: 1,
            FillColorGreen: 1,
            FillColorBlue: 1,
            OutlineEnabled: 1,
            OutlineThickness: 0.08,
            OutlineColorRed: 0,
            OutlineColorGreen: 0.25433526011561,
            OutlineColorBlue: 1,
            ShadowEnabled: 0,
            ShadowColorRed: 0,
            ShadowColorGreen: 0,
            ShadowColorBlue: 0,
            HighlightStyle: 3,
            HighlightEnabled: 0,
        },
    },
    {
        id: 'builtin:chalkboard-bold',
        name: 'Chalkboard Bold',
        description: 'Bold chalkboard style with yellow highlights and outline.',
        builtIn: true,
        version: 1,
        createdAt: EPOCH,
        updatedAt: EPOCH,
        macroSettings: {
            Font: 'Chalkboard',
            Style: 'Bold',
            TextSize: 0.07,
            TextPosition: [0.5, 0.12, 0],
            FadeEnabled: 0,
            PopInEnabled: 0,
            SlideUpEnabled: 0,
            AnimationLength: 0.12,
            AnimationLevel: 0,
            AnimationMode: 0,
            HighlightExtendHorizontal: 0,
            HighlightExtendVertical: 0,
            HighlightRound: 0.2,
            HighlightColorRed: 1,
            HighlightColorGreen: 0.90344,
            HighlightColorBlue: 0.29,
            FillEnabled: 1,
            FillColorRed: 1,
            FillColorGreen: 1,
            FillColorBlue: 1,
            OutlineEnabled: 1,
            OutlineThickness: 0.08,
            OutlineColorRed: 0,
            OutlineColorGreen: 0,
            OutlineColorBlue: 0,
            ShadowEnabled: 1,
            ShadowColorRed: 0,
            ShadowColorGreen: 0,
            ShadowColorBlue: 0,
            HighlightStyle: 0,
            HighlightEnabled: 1,
        },
    },
    {
        id: 'builtin:menlo-bold-red',
        name: 'Menlo Bold Red',
        description: 'Monospace font with red highlights and black outline.',
        builtIn: true,
        version: 1,
        createdAt: EPOCH,
        updatedAt: EPOCH,
        macroSettings: {
            Font: 'Menlo',
            Style: 'Bold',
            TextSize: 0.07,
            TextPosition: [0.5, 0.12, 0],
            FadeEnabled: 0,
            PopInEnabled: 0,
            SlideUpEnabled: 0,
            AnimationLength: 0.12,
            AnimationLevel: 0,
            AnimationMode: 0,
            HighlightExtendHorizontal: -0.04,
            HighlightExtendVertical: 0,
            HighlightRound: 0.2,
            HighlightColorRed: 1,
            HighlightColorGreen: 0,
            HighlightColorBlue: 0,
            FillEnabled: 1,
            FillColorRed: 1,
            FillColorGreen: 1,
            FillColorBlue: 1,
            OutlineEnabled: 1,
            OutlineThickness: 0.08,
            OutlineColorRed: 0,
            OutlineColorGreen: 0,
            OutlineColorBlue: 0,
            ShadowEnabled: 1,
            ShadowColorRed: 0,
            ShadowColorGreen: 0,
            ShadowColorBlue: 0,
            HighlightStyle: 3,
            HighlightEnabled: 1,
        },
    },
    {
        id: 'builtin:futura-bold-blue',
        name: 'Futura Bold Blue',
        description: 'Clean sans-serif with blue highlights and no outline.',
        builtIn: true,
        version: 1,
        createdAt: EPOCH,
        updatedAt: EPOCH,
        macroSettings: {
            Font: 'Futura',
            Style: 'Bold',
            TextSize: 0.07,
            TextPosition: [0.5, 0.12, 0],
            FadeEnabled: 0,
            PopInEnabled: 0,
            SlideUpEnabled: 0,
            AnimationLength: 0.12,
            AnimationLevel: 0,
            AnimationMode: 0,
            HighlightExtendHorizontal: -0.03,
            HighlightExtendVertical: 0.06,
            HighlightRound: 0.2,
            HighlightColorRed: 0,
            HighlightColorGreen: 0.208,
            HighlightColorBlue: 1,
            FillEnabled: 1,
            FillColorRed: 1,
            FillColorGreen: 1,
            FillColorBlue: 1,
            OutlineEnabled: 0,
            OutlineThickness: 0.08,
            OutlineColorRed: 0,
            OutlineColorGreen: 0,
            OutlineColorBlue: 0,
            ShadowEnabled: 0,
            ShadowColorRed: 0,
            ShadowColorGreen: 0,
            ShadowColorBlue: 0,
            HighlightStyle: 3,
            HighlightEnabled: 1,
        },
    },
];

export const DEFAULT_PRESET_ID = BUILT_IN_PRESETS[0].id;

export const isBuiltInPresetId = (id: string) => id.startsWith('builtin:');
