name: Package AutoSubs for MacOS
on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout AutoSubs Repo Code
      uses: actions/checkout@v4
        
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 24

    - name: Import Apple Certificates
      env:
        APP_CERTIFICATE_BASE64: ${{ secrets.APPLE_SIGNING_CERTIFICATE }}
        APP_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
        INSTALLER_CERTIFICATE_BASE64: ${{ secrets.APPLE_INSTALLER_CERTIFICATE }}
        INSTALLER_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        APPLE_NOTARIZE_KEY: ${{ secrets.APPLE_NOTARIZE_KEY }}
        APPLE_NOTARIZE_ID: ${{ secrets.APPLE_NOTARIZE_ID }}
        APPLE_ISSUER: ${{ secrets.APPLE_ISSUER }}

      run: |
        # Define paths
        APP_CERT_PATH=$RUNNER_TEMP/app_certificate.p12
        INSTALLER_CERT_PATH=$RUNNER_TEMP/installer_certificate.p12
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

        # Decode and save certificates
        echo "$APP_CERTIFICATE_BASE64" | base64 --decode > $APP_CERT_PATH
        echo "$INSTALLER_CERTIFICATE_BASE64" | base64 --decode > $INSTALLER_CERT_PATH

        # Create and configure temporary keychain
        security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security list-keychains -s $KEYCHAIN_PATH

        # Import Application certificate
        security import $APP_CERT_PATH -P "$APP_CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

        # Import Installer certificate
        security import $INSTALLER_CERT_PATH -P "$INSTALLER_CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

        # Import Notarization credentials
        echo "$APPLE_NOTARIZE_KEY" | base64 --decode > Notarization_AuthKey.p8
        xcrun notarytool store-credentials "AC_PASSWORD" \
          --key "Notarization_AuthKey.p8" \
          --key-id "$APPLE_NOTARIZE_ID" \
          --issuer "$APPLE_ISSUER"
      
    - name: Install Dependencies
      run: |
        cd AutoSubs-App
        npm install

    - name: Download ffmpeg/ffprobe binaries
      run: |
        set -euo pipefail
        cd AutoSubs-App/src-tauri
        mkdir -p binaries
        cd binaries

        # Determine architecture and corresponding asset names
        ARCH=$(uname -m)
        if [ "$ARCH" = "arm64" ]; then
          ZIP_NAME="ffmpeg-aarch64-apple-darwin.zip"
          FFMPEG_SRC="ffmpeg-aarch64-apple-darwin"
          FFPROBE_SRC="ffprobe-aarch64-apple-darwin"
        else
          # Fallback to x86_64 naming if runner arch isn't arm64
          ZIP_NAME="ffmpeg-x86_64-apple-darwin.zip"
          FFMPEG_SRC="ffmpeg-x86_64-apple-darwin"
          FFPROBE_SRC="ffprobe-x86_64-apple-darwin"
        fi

        # Download the appropriate archive from the ffmpeg-binaries repo
        gh release download \
          --repo tmoroney/ffmpeg-binaries \
          --pattern "$ZIP_NAME" \
          --clobber

        # Unzip directly into current folder (junk paths to avoid nested dirs)
        unzip -jo "$ZIP_NAME"

        # Ensure executables (keep architecture-specific names expected by Tauri v2)
        chmod +x "$FFMPEG_SRC" "$FFPROBE_SRC"

        # Cleanup archive
        rm -f "$ZIP_NAME"

    - name: Bundle Tauri App
      run: |
        cd AutoSubs-App
        export APPLE_SIGNING_IDENTITY="Developer ID Application: ${{ secrets.APPLE_IDENTITY }}"
        npm run tauri build

    - name: Create Mac Package
      run: |
        # Create the package directory
        mkdir Mac-Package/Payload

        # Move the app to the package
        mv AutoSubs-App/src-tauri/target/release/bundle/macos/AutoSubs.app Mac-Package/Payload

    - name: Create PKG Installer
      run: |
        # Give permissions to the scripts
        chmod +x Mac-Package/Scripts/*

        # Create the package
        pkgbuild --identifier com.tom-moroney.autosubs \
          --version 3.0 \
          --install-location "/Applications" \
          --root Mac-Package/Payload \
          --scripts Mac-Package/Scripts \
          AutoSubs-unsigned.pkg

    - name: Sign PKG Installer
      run: |
        productsign --sign "Developer ID Installer: ${{ secrets.APPLE_IDENTITY }}" \
          --timestamp \
          "AutoSubs-unsigned.pkg" \
          "AutoSubs-Mac-ARM.pkg"

    - name: Notarize PKG Installer
      run: |
        # Function to notarize and staple the package
        notarize_and_staple() {
          xcrun notarytool submit "AutoSubs-Mac-ARM.pkg" \
            --keychain-profile "AC_PASSWORD" \
            --wait
        
          xcrun stapler staple "AutoSubs-Mac-ARM.pkg"
        }
        
        # Try notarization up to 3 times in case of bus error
        for i in {1..3}; do
          notarize_and_staple && break || {
            echo "Notarization attempt $i failed. Retrying..."
            sleep 10
          }
        done

    - name: Upload Asset to Release
      uses: softprops/action-gh-release@v2
      with:
        files: AutoSubs-Mac-ARM.pkg
        token: ${{ secrets.GH_TOKEN }}
        tag_name: ${{ github.event.release.tag_name }}